### ISSUE TITLE
Add validation message theming in vscode-text-field

### ISSUE THREAD

**Issue by kevin-s-wang** [microsoft/vscode-webview-ui-toolkit#403] opened 2022-09-13 08:48 UTC
### Feature request

Add validation message theming in `vscode-text-field`

### Expected behavior
Just like the one in vscode:
<img width="156" alt="image" src="https://user-images.githubusercontent.com/24372742/189855744-20987819-c007-4dcc-9c67-94b7426e9f7a.png">

### Current behavior

No such validation message theming support

### Use case

Let users be aware of the wrong values and provide tips for them

### Screenshots/references

<img width="156" alt="image" src="https://user-images.githubusercontent.com/24372742/189856212-568bacd3-102f-48d2-9d75-cba5913e61f4.png">

**Comment by daviddossett** [comment] 2022-09-13 17:11
Thanks @kevin-s-wang! Closing given the duplicate of #270. We definitely want to do this.

**Closed by daviddossett** 2022-09-13 17:11 UTC
Labels: enhancement
