### ISSUE TITLE
Upgrade `fast-foundations` package to adopt latest `tabpanel` template

### ISSUE THREAD

**Issue by RealKai42** [microsoft/vscode-webview-ui-toolkit#502] opened 2023-08-21 06:18 UTC
### Describe the bug

We cannot customize the CSS of `class="tabpanel"` element like:
![MicrosoftTeams-image](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/44634134/88608d88-ba1e-4b62-8de2-77ddd528ba45)

we may solve it by upgrade the @microsoft/fast-foundation version, for the latest version it add part="tabpanel" to it 
<img width="689" alt="CleanShot 2023-08-21 at 14 15 07@2x" src="https://github.com/microsoft/vscode-webview-ui-toolkit/assets/44634134/60708b80-c265-4326-8ffa-309e7daa0fc4">

### Desktop (please complete the following information):

-   OS Version: [e.g. `macOS 11.3.1`]
-   Toolkit Version: [e.g. `v0.8.0`]

**Comment by hawkticehurst** [comment] 2023-10-06 23:34
Hey @RealKai42! Correct, at this time it is expected behavior that you cannot customize the `div` with `class="tabpanel"` (as a result of the rules of the [Shadow DOM Web API](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM)). 

As you've seemingly discovered we use an older version of the FAST Foundation components that do not include a `part="tabpanel"` attribute in the `tabs` component template. As a result, you are also correct that upgrading the `@microsoft/fast-foundations` package to the latest stable version should solve this problem since it does now include a `part="tabpanel"` attribute!

Since this is expected behavior in the current version I'm actually going to re-label this as an `enhancement` request to upgrade our dependency on `fast-foundations` rather than a `bug` and will add it to our backlog to upgrade our dependency on FAST.

**Comment by hawkticehurst** [comment] 2023-10-06 23:37
Oh I actually have one more question: Why do you want to restyle the `tabpanel` element? 

We've done our best to match the look and feel of native VS Code UI and generally recommend that developers _do not_ override those styles/behaviors. But if our current `vscode-panels` component is not serving your needs I'd love to hear more about why that is and what you're looking for 😊

**Comment by RealKai42** [comment] 2023-10-07 07:51
@hawkticehurst  I don't know whether it's an edge case
I need `tabpanel` to have a fixed height to make one of its child element scrollable

like this screenshot, only the data panel is scrollable.  
currently, I use a hack way to make `tabpanel` have style like this
```js
      tabPanelElement.style.height = "100%";
      tabPanelElement.style.maxHeight = "100%";
      tabPanelElement.style.overflow = "hidden";
```
![CleanShot Aug 18](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/44634134/62af39e3-5af7-4d51-a1a2-6f99d6ba429a)


If without this style, it will be:
![CleanShot Aug 18 (1)](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/44634134/fe820b32-209d-4036-a7db-c417740ea2ba)

**Comment by hawkticehurst** [comment] 2023-10-10 21:55
Oooh! I totally got it now –– thank you for the gifs btw they are very helpful.

In that case, I'd consider this underlying core request to be a duplicate of #464. 

I had originally labeled that issue as an enhancement request but as I'm thinking more about it now, I think you are both right that this is a bug since native VS Code panels have overscroll behavior built in. I'm going to go ahead and close this issue and then change #464 back to being a bug request and will try address this in the coming weeks.

Hope that all makes sense, but please let me know if you disagree and/or have any other questions/comments 😊

**Closed by hawkticehurst** 2023-10-10 21:55 UTC
Labels: enhancement

**Comment by hawkticehurst** [comment] 2023-10-10 22:06
For what it's worth, I'm also planning on updating our FAST dependencies to the latest stable versions in the coming weeks, but I believe adding overscroll support to the `vscode-panels` component should be a better solution than making you and other developers implement that behavior yourself :)
