### ISSUE TITLE
I'm getting ts compile errors on ffast-foundation when using this toolkit

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-webview-ui-toolkit#479] opened 2023-05-12 16:15 UTC
### Describe the bug

I've included this toolkit in my vscode extension and webview using:

```
import { provideVSCodeDesignSystem, vsCodeButton, vsCodeTag } from "@vscode/webview-ui-toolkit";
provideVSCodeDesignSystem().register(vsCodeButton(), vsCodeTag());
```

(after npm install of course)

Then during compile I'm getting:

```
[{
	"resource": "/d:/GitHub/mympclient/node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts",
	"owner": "typescript",
	"code": "2344",
	"severity": 8,
	"message": "Type 'T' does not satisfy the constraint 'string | number | boolean | symbol | any[] | Uint8Array | ({ createCSS?(): string; } & Record<PropertyKey, any>) | null'.\n  Type 'T' is not assignable to type '{ createCSS?(): string; } & Record<PropertyKey, any>'.\n    Type 'T' is not assignable to type '{ createCSS?(): string; }'.",
	"source": "ts",
	"startLineNumber": 2252,
	"startColumn": 66,
	"endLineNumber": 2252,
	"endColumn": 67,
	"relatedInformation": [
		{
			"startLineNumber": 2252,
			"startColumn": 25,
			"endLineNumber": 2252,
			"endColumn": 26,
			"message": "This type parameter might need an `extends { createCSS?(): string; }` constraint.",
			"resource": "/d:/GitHub/mympclient/node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts"
		},
		{
			"startLineNumber": 2252,
			"startColumn": 25,
			"endLineNumber": 2252,
			"endColumn": 26,
			"message": "This type parameter might need an `extends { createCSS?(): string; } & Record<PropertyKey, any>` constraint.",
			"resource": "/d:/GitHub/mympclient/node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts"
		},
		{
			"startLineNumber": 2252,
			"startColumn": 25,
			"endLineNumber": 2252,
			"endColumn": 26,
			"message": "This type parameter might need an `extends string | number | boolean | symbol | any[] | Uint8Array | ({ createCSS?(): string; } & Record<PropertyKey, any>) | null` constraint.",
			"resource": "/d:/GitHub/mympclient/node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts"
		}
	]
},{
	"resource": "/d:/GitHub/mympclient/node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts",
	"owner": "typescript",
	"code": "2344",
	"severity": 8,
	"message": "Type 'T' does not satisfy the constraint 'string | number | boolean | symbol | any[] | Uint8Array | ({ createCSS?(): string; } & Record<PropertyKey, any>) | null'.\n  Type 'T' is not assignable to type '{ createCSS?(): string; } & Record<PropertyKey, any>'.\n    Type 'T' is not assignable to type '{ createCSS?(): string; }'.",
	"source": "ts",
	"startLineNumber": 2254,
	"startColumn": 186,
	"endLineNumber": 2254,
	"endColumn": 187,
	"relatedInformation": [
		{
			"startLineNumber": 2254,
			"startColumn": 25,
			"endLineNumber": 2254,
			"endColumn": 26,
			"message": "This type parameter might need an `extends { createCSS?(): string; }` constraint.",
			"resource": "/d:/GitHub/mympclient/node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts"
		},
		{
			"startLineNumber": 2254,
			"startColumn": 25,
			"endLineNumber": 2254,
			"endColumn": 26,
			"message": "This type parameter might need an `extends { createCSS?(): string; } & Record<PropertyKey, any>` constraint.",
			"resource": "/d:/GitHub/mympclient/node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts"
		},
		{
			"startLineNumber": 2254,
			"startColumn": 25,
			"endLineNumber": 2254,
			"endColumn": 26,
			"message": "This type parameter might need an `extends string | number | boolean | symbol | any[] | Uint8Array | ({ createCSS?(): string; } & Record<PropertyKey, any>) | null` constraint.",
			"resource": "/d:/GitHub/mympclient/node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts"
		}
	]
},{
	"resource": "/d:/GitHub/mympclient/node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts",
	"owner": "typescript",
	"code": "2344",
	"severity": 8,
	"message": "Type 'T' does not satisfy the constraint 'string | number | boolean | symbol | {} | any[] | Uint8Array | null'.\n  Type 'T' is not assignable to type 'Uint8Array'.",
	"source": "ts",
	"startLineNumber": 2256,
	"startColumn": 121,
	"endLineNumber": 2256,
	"endColumn": 122,
	"relatedInformation": [
		{
			"startLineNumber": 2256,
			"startColumn": 25,
			"endLineNumber": 2256,
			"endColumn": 26,
			"message": "This type parameter might need an `extends Uint8Array` constraint.",
			"resource": "/d:/GitHub/mympclient/node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts"
		},
		{
			"startLineNumber": 2256,
			"startColumn": 25,
			"endLineNumber": 2256,
			"endColumn": 26,
			"message": "This type parameter might need an `extends string | number | boolean | symbol | {} | any[] | Uint8Array | null` constraint.",
			"resource": "/d:/GitHub/mympclient/node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts"
		}
	]
}]
```
I was previously getting 247 errors but added these compiler options and now have only these 3:
```
"lib": [
			"ES2020", "dom"
		],
```

**Comment by hawkticehurst** [comment] 2023-05-12 23:22
Thanks for the report! I think I know where this might be stemming from, but just a few more Qs:

- What version of the typescript are you using?
- What version of VS Code are you using? Aka what's the `engine` field in `package.json` say?
- Are you using the toolkit web components or React components?
- What build tool are you using (webpack, esbuild, etc)?

Also, in general, if you're able to share a link to a GitHub repo with the code/extension (or a small reproduction of the issue) that would be immensely helpful :)

**Comment by timheuer** [comment] 2023-05-12 23:34
> * What version of the typescript are you using?

4.9.5

> * What version of VS Code are you using? Aka what's the `engine` field in `package.json` say?

^1.78.0

> * Are you using the toolkit web components or React components?

Toolkit web components -- no React in play

> * What build tool are you using (webpack, esbuild, just the typescript compiler, etc)?

For now just the ts compiler

> Also, in general, if you're able to share a link to a GitHub repo with the code/extension (or a small reproduction of the issue) that would be immensely helpful :)

It's a private project now, I can add you but I haven't checked in the webui stuff because it's not compiling ;-)

**Comment by hawkticehurst** [comment] 2023-05-12 23:36
Thank you! Also yes, adding me to the repo would decidedly be helpful

**Comment by timheuer** [comment] 2023-05-12 23:49
Done, I created a branch for you and checked in the non-working stash for now.

**Comment by timheuer** [comment] 2023-05-13 00:29
okay @hawkticehurst - for simplicity here's the basic repro: https://github.com/timheuer/webuitoolkitbug

I added the initial 247 error output when just adding it, then the only 3 error output when i add `DOM` to the tsconfig.

**Comment by hawkticehurst** [comment] 2023-05-15 19:46
Okay, I've looked over everything and I believe the core issue is that you're trying to register the toolkit components outside a webview panel. 

The gist is you cannot import/register the toolkit components inside of a file like `extension.ts` because it will be executed as a Node process, whereas a webview is an `iframe` under the hood and executes code in a browser-like environment –– toolkit components need to be executed in a browser environment

For practical purposes, this basically means instead of importing/registering toolkit components within `extension.ts` or a `MyWebviewPanel.ts` file, you instead need to import/register the components into a JS/TS file that will be inserted/executed in a webview iframe (such as `webview.js`)

```js
import { provideVSCodeDesignSystem, vsCodeButton } from "@vscode/webview-ui-toolkit";
provideVSCodeDesignSystem().register(vsCodeButton());

// ... other webview.js code ...
```

```ts
private _getHtmlForWebview( ... ) {
  const webviewScript = webview.asWebviewUri(vscode.Uri.joinPath(this._extensionUri, "media", "webview.js"));
  
  // ... other stuff ...

  return /*html*/ `
    <!DOCTYPE html>
    <html>
      <head>
        <!-- other stuff -->
      </head>
      <body>
        <!-- other stuff -->
        <vscode-button>Hello world!</vscode-button>
        <script nonce="${nonce}" src="${webviewScript}"></script>
      </body>
    </html>
`;
}
```

More than happy to explain more, but if you haven't already read over/followed the [getting started guide](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/docs/getting-started.md) and/or looked at/cloned our [hello-world sample extension](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/default/hello-world) those would be great resources to look at

**Comment by hawkticehurst** [comment] 2023-05-16 02:35
Going to go ahead and close this based on our offline chat earlier today! Feel free to open a new issue if you have any more issues or questions!

**Closed by hawkticehurst** 2023-05-16 02:35 UTC
Labels: bug
