### ISSUE TITLE
vscode-text-field doesn't appear to support a type = "number"? 

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vscode-webview-ui-toolkit#491] opened 2023-06-15 22:38 UTC
The documentation for vscode-text-field states:
![image](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/46171060/683e92cb-2653-4e42-abc8-7276e2ecce7d)

I find no mention of the ability to handle a numeric input field.

**Comment by hawkticehurst** [comment] 2023-06-15 23:39
Thanks for the issue! 

This is actually a duplicate of #439 so I'm going to close this, but to provide some context:

The toolkit is built using a web component framework called [FAST](https://www.fast.design/). In particular, FAST provides a [package of unstyled base components](https://github.com/microsoft/fast/tree/master/packages/web-components/fast-foundation) that we use. In this package, FAST decided to split text fields and number fields into separate components, so the lack of `type="number"` in the `vscode-text-field` is actually intentional in this case.

On the toolkit side, we haven't added a `vscode-number-field` component at this point because we've tried to keep the toolkit limited to components that already exist in the VS Code core UI (and a number field isn't one of those components). We may change this stance in the future, but like I said in another issue we're very tightly resourced at this time so adding new components to the toolkit isn't something we can really do right now even if we wanted to.

Hope you understand and that that insight is helpful! Let me know if you have any more questions

**Closed by hawkticehurst** 2023-06-15 23:39 UTC
Labels: bug

**Comment by davidkjackson54** [comment] 2023-06-15 23:52
Understood. I hadn't found the duplicate till you mentioned it.

**Comment by hawkticehurst** [comment] 2023-06-15 23:57
No worries at all!
