### ISSUE TITLE
[Feature Request] Tree component or TreeView wrapper

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode-webview-ui-toolkit#425] opened 2022-12-06 19:51 UTC
### Feature request

I want to be able to put a tree in the same webview as other arbitrary components.

### Expected behavior

Ideally, it would be nice if `vscode-webview-ui-toolkit` provided some kind component wrapper for the VSCode `TreeView` API so I can merge my existing `TreeView` into my webview.

Or maybe instead of anything in this library, the VSCode Extension API could provide an API to create a merged webview/`TreeView`.

### Current behavior

Right now I have to use a separate `TreeView` from the webview, or implement my own tree component(s) for the webview.

### Use case

I'm working on this extension: https://github.com/codemodsquad/vscode-astx
I'm modeling the UI after the builtin Search view.

### Screenshots/references

See how I have a separate *Search* and *Matches* views in this screenshot.  I'd like to be able to combine them into a single view.

![Screenshot](https://github.com/codemodsquad/vscode-astx/raw/beta/screenshot.png)

**Comment by hawkticehurst** [comment] 2022-12-06 23:47
Thanks for the feature request!

I'm actually going to close this as it is a duplicate of #255 but we'll definitely keep your specific request in mind as we continue to think about the possibility of adding some kind of tree view 

> Ideally, it would be nice if vscode-webview-ui-toolkit provided some kind of component wrapper for the VSCode TreeView API so I can merge my existing TreeView into my webview.

Love this idea and have actually done a handful of explorations during the last 2 years on the possibility of exposing core VS Code UI components/APIs as webview toolkit components but it has proven to be **_exceedingly_** hard to achieve

It would likely require a ton of coordination/effort between core VS Code engineers and those working on the toolkit –– something that is unlikely to happen since we're both very small teams with limited bandwidth at this time unfortunately

> Right now I have to use a separate TreeView from the webview

This is the recommended way of tackling TreeView-related goals/features since the core API is going to be far more performant and accessible than a webview-based implementation so I would recommend sticking with that at this time

**Closed by hawkticehurst** 2022-12-06 23:47 UTC
Labels: enhancement
