### ISSUE TITLE
How to use in vanilla html?

### ISSUE THREAD

**Issue by axelthat2** [microsoft/vscode-webview-ui-toolkit#347] opened 2022-03-03 05:01 UTC
### Describe the bug

When I try to use the vscode webview components in my vanilla app, I get the error,
```
controller.js:363 Uncaught Error: Missing FASTElement definition.
    at Function.forCustomElement (controller.js:363:19)
    at new <anonymous> (fast-element.js:9:24)
    at new FoundationElement (foundation-element.js:14:9)
    at new _Button (button.form-associated.js:3:1)
    at new C (form-associated.js:19:13)
    at new FormAssociatedButton (button.form-associated.js:12:9)
    at new Button (button.js:14:9)
    at new Button2 (index.js:12:8)
    at main.ts:4:16
```

### To reproduce

1. `git clone https://github.com/axelthat2/vscode-bug`
2. Open developer tools and you can see the error.

### Expected behavior

Web components to work.

### Screenshots

<img width="1673" alt="Screen Shot 2022-03-03 at 10 45 34 AM" src="https://user-images.githubusercontent.com/91611516/156499402-7e415e00-a2d8-46c4-88de-307bbc5c9442.png">

### Desktop (please complete the following information):

-   OS Version: macOS 12.2.1
-   Toolkit Version: ^0.9.1

**Comment by hawkticehurst** [comment] 2022-03-03 19:56
Hey, @axelthat2 I checked out your repo (thanks for providing a reproduction of the issue!) and it seems like a simple case of using the incorrect functions/API to set up the components properly.

Change your `src/main.ts` file to include the following:

```ts
import { provideVSCodeDesignSystem, vsCodeButton } from "@vscode/webview-ui-toolkit"

provideVSCodeDesignSystem().register(vsCodeButton());
```

Also if you want to use other components, simply import the desired component function (always in the form `vsCode{ComponentName}` and then add it to the `register` method.

```ts
import { 
  provideVSCodeDesignSystem, 
  vsCodeButton, 
  vsCodeCheckbox 
} from "@vscode/webview-ui-toolkit"

provideVSCodeDesignSystem().register(vsCodeButton(), vsCodeCheckbox());
```

**Comment by hawkticehurst** [comment] 2022-03-03 20:04
I'm also going to go ahead and close this issue and open a new one about updating our documentation to better highlight this information since up to this point this method of using the toolkit components isn't that well documented, except in [fairly deep issue threads](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/283#issuecomment-961103031) and also in the [FAST getting started guide](https://www.fast.design/docs/components/getting-started) (which I don't expect most toolkit users to ever see).

With that said, if you have any more questions, comments, concerns, etc. about this specific issue feel free to add more comments to this thread and I'll keep an eye on it over the next couple of days!

**Closed by hawkticehurst** 2022-03-03 20:04 UTC
Labels: bug

**Comment by axelthat2** [comment] 2022-03-04 08:57
Thank you so much. That helps a lot. I tried going through the toolkit docs and couldn't find anything. Adding doc for this issue will be so much great. Again thank you for your swift response.

**Comment by hawkticehurst** [comment] 2022-03-04 18:48
You're welcome, happy to hear it was helpful!
